"""Regenerate docs/evidence/convergence.md from the pricers themselves.

    python scripts/generate_evidence.py           # write the artifact
    python scripts/generate_evidence.py --check   # fail if it would change

The artifact is committed, and `--check` is what makes committing it safe: a
number in the README that nobody can reproduce is a claim, not evidence. Every
figure here is deterministic — the stochastic methods are seeded, and each
value is rounded before it is written — so a clean checkout reproduces the
committed file byte for byte.

Deliberately excluded: timings. They are the one thing that cannot reproduce,
and they live in docs/evidence/benchmarks.md with their own hardware caveat.
"""

import argparse
import itertools
import sys
from pathlib import Path

from pricing import AMERICAN_METHODS, EUROPEAN_METHODS, American_Option, European_Option

sys.path.insert(0, str(Path(__file__).parent.parent / "tests"))
from reference_values import (  # noqa: E402
    HULL_AMERICAN_CONVERGED,
    HULL_AMERICAN_FIVE_STEP,
    HULL_EUROPEAN,
)

OUTPUT = Path(__file__).parent.parent / "docs" / "evidence" / "convergence.md"

TREE_STEPS = 200
MC_PATHS, MC_STEPS = 50_000, 50
LSMC_PATHS = 20_000
SEED = 42

K, R, SIG, DIVIDEND = 100.0, 0.05, 0.25, 0.03
MONEYNESS = [0.8, 0.9, 1.0, 1.1, 1.2]
MATURITIES = [0.5, 1.0]

GREEKS = ["delta", "gamma", "theta", "vega", "rho"]


def price(style, kind, S, y, T, method, K=K, r=R, sig=SIG):
    cls = European_Option if style == "european" else American_Option
    opt = cls(kind, S, K, r, sig, y, T, method)
    if method in ("BT", "TT"):
        opt.setTreeSteps(TREE_STEPS)
    elif method == "MC":
        opt.setSeedVariables(SEED, MC_PATHS, T / MC_STEPS)
    elif method == "LSMC":
        opt.setSeedVariables(SEED, LSMC_PATHS)
    if method == "BSM":
        return opt.BSM().price
    return float(opt.method())


def convergence_table(style, methods):
    lines = [
        "| Moneyness | T | " + " | ".join(methods) + " | Max spread |",
        "|---|---|" + "---|" * (len(methods) + 1),
    ]
    worst = 0.0
    for m, T in itertools.product(MONEYNESS, MATURITIES):
        values = [price(style, "call", m * K, DIVIDEND, T, meth) for meth in methods]
        spread = max(values) - min(values)
        worst = max(worst, spread)
        cells = " | ".join(f"{v:.4f}" for v in values)
        lines.append(f"| {m:.1f} | {T:.2f} | {cells} | {spread:.4f} |")
    return "\n".join(lines), worst


def greek_table():
    lines = [
        "| Moneyness | T | " + " | ".join(g.capitalize() for g in GREEKS) + " |",
        "|---|---|" + "---|" * len(GREEKS),
    ]
    worst = 0.0
    for m, T in itertools.product(MONEYNESS, MATURITIES):
        args = ("call", m * K, K, R, SIG, DIVIDEND, T)
        fd = European_Option(*args, "FD").priceOption()
        exact = European_Option(*args, "BSM").priceOption()
        cells = []
        for greek in GREEKS:
            a, b = getattr(fd, greek), getattr(exact, greek)
            rel = abs(a - b) / max(abs(b), 1e-12)
            worst = max(worst, rel)
            cells.append(f"{rel * 100:.2f}%")
        lines.append(f"| {m:.1f} | {T:.2f} | " + " | ".join(cells) + " |")
    return "\n".join(lines), worst


def anchor_table():
    rows = []
    p = HULL_EUROPEAN["params"]
    for kind in ("call", "put"):
        printed = HULL_EUROPEAN[kind]
        for method in EUROPEAN_METHODS:
            got = price("european", kind, p["S"], p["y"], p["T"], method, p["K"], p["r"], p["sig"])
            rows.append(
                f"| European {kind} | {method} | {printed:.2f} | {got:.4f} | {got - printed:+.4f} |"
            )

    a = HULL_AMERICAN_FIVE_STEP
    q = a["params"]
    opt = American_Option("put", q["S"], q["K"], q["r"], q["sig"], q["y"], q["T"], "BT")
    opt.setTreeSteps(a["steps"])
    got = float(opt.BT())
    rows.append(
        f"| American put, {a['steps']}-step tree | BT | {a['put']:.2f} | {got:.4f} | {got - a['put']:+.4f} |"
    )

    c = HULL_AMERICAN_CONVERGED
    q = c["params"]
    for method in ("BT", "TT", "FD"):
        got = price("american", "put", q["S"], q["y"], q["T"], method, q["K"], q["r"], q["sig"])
        rows.append(
            f"| American put, converged | {method} | {c['put']:.4f} | {got:.4f} | {got - c['put']:+.4f} |"
        )

    header = [
        "| Contract | Method | Reference | This library | Difference |",
        "|---|---|---|---|---|",
    ]
    return "\n".join(header + rows)


def render():
    european, eu_worst = convergence_table("european", list(EUROPEAN_METHODS))
    american, am_worst = convergence_table("american", list(AMERICAN_METHODS))
    greeks, greek_worst = greek_table()

    return f"""# Convergence evidence

Generated by `scripts/generate_evidence.py`. Do not edit by hand — the
generator is run with `--check` to confirm this file reproduces byte for byte,
so an edit here becomes a failure rather than a correction.

Six methods, none sharing an implementation path: a closed form, two lattices,
two Monte Carlo estimators, and a PDE solver. Agreement between them is the
claim, and the point of having six is that a mistake would have to be made
identically in several to survive.

Contracts below are calls at strike {K:.0f}, rate {R:.2f}, volatility {SIG:.2f},
dividend yield {DIVIDEND:.2f}. Trees use {TREE_STEPS} steps, Monte Carlo
{MC_PATHS:,} paths, Longstaff-Schwartz {LSMC_PATHS:,}, all seeded.

## European methods

Worst spread across the grid: **{eu_worst:.4f}**.

{european}

## American methods

No closed form exists, so these agree only with each other. Longstaff-Schwartz
is biased low by construction, which is most of the spread.

Worst spread across the grid: **{am_worst:.4f}**.

{american}

## Greeks against closed form

Finite-difference Greeks as a relative error against Black-Scholes. Delta and
gamma come from spatial differences on the solver's own grid; theta, vega and
rho from central differences with a bump scaled to each input.

Worst relative error: **{greek_worst * 100:.2f}%**. Rho is the loosest, and the
reason is that these errors are inherited rather than introduced — a method
whose price is 0.95% out cannot produce a rho that is better.

{greeks}

## Against an outside reference

**Read the caveat before citing this section.** The parameter sets and printed
values are Hull's, but the edition and page could not be verified, so this is
not yet an external anchor in the sense R31 asks for. What it is: agreement
with an independent implementation in `tests/reference_values.py` that shares
no code with `pricing/`, reproducing the printed figures to their stated
precision.

One trap the table encodes. Hull's 4.49 for the American put is the output of a
**five-step** tree, not a converged price — the converged value is 4.2842.
Checking a 200-step method against 4.49 would be wrong by 0.2 while looking
correct, so the five-step row pins the five-step tree and the converged rows
are labelled as this library's own number.

{anchor_table()}
"""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the artifact would change")
    args = parser.parse_args()

    generated = render()

    if args.check:
        if not OUTPUT.exists():
            print(f"{OUTPUT} does not exist; run without --check")
            return 1
        if OUTPUT.read_text() != generated:
            print(f"{OUTPUT} is stale — regenerate with scripts/generate_evidence.py")
            return 1
        print(f"{OUTPUT} reproduces byte for byte")
        return 0

    OUTPUT.write_text(generated)
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
